"""Add solutions

Revision ID: ab759ebbd843
Revises: 9780fcfe21b4
Create Date: 2024-10-30 02:50:43.182719

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ab759ebbd843"
down_revision = "9780fcfe21b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("solutions", postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "solutions")
    # ### end Alembic commands ###
